include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

check-ontologies-parse:
  extends: .style
  script:
    - python -m pip install .[dev]
    - python ontologies/parse.py
    - git diff --exit-code

test-3.8:
  extends: .test-3.8

test-3.9-win:
  extends: .test-3.9-win

test-3.13:
  extends: .test-3.13

build_sdist:
  extends: .build_sdist

test_sdist-3.8:
  extends: .test_sdist-3.8

test_sdist-3.9:
  extends: .test_sdist-3.9

test_sdist-3.10:
  extends: .test_sdist-3.10

test_sdist-3.10-win:
  extends: .test_sdist-3.10-win

test_sdist-3.11:
  extends: .test_sdist-3.11

test_sdist-3.12:
  extends: .test_sdist-3.12

test_sdist-3.13:
  extends: .test_sdist-3.13

build_doc:
  extends: .build_doc

pypi:
  extends: .pypi

testpypi:
  extends: .testpypi

pages:
  extends: .pages

assets:
  extends: .assets
