name: Publish to PyPI

on:
  workflow_dispatch:

permissions:
  contents: write  # This grants permission to create tags

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  test:
    name: Test package
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install built distributions
        run: pip install "$(ls dist/*.tar.gz)"[test]

      - name: Run tests
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          DISTRO_NAME="${REPO_NAME//-/_}"
          pytest --pyargs ${DISTRO_NAME}

  publish-test-pypi:
    name: Publish to TestPyPI
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install twine

      - name: Publish package to TestPyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          if [[ -z "${{ env.TWINE_PASSWORD }}" ]]; then
            echo "❌ TEST_PYPI_TOKEN is not set."
            exit 1
          fi
          # twine upload --repository testpypi dist/*  TODO: uncomment when tested

  publish-pypi:
    name: Publish to PyPI
    needs: publish-test-pypi
    runs-on: ubuntu-latest

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install twine

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          if [[ -z "${{ env.TWINE_PASSWORD }}" ]]; then
            echo "❌ PYPI_TOKEN is not set."
            exit 1
          fi
          # twine upload dist/*   TODO: uncomment when tested

  tag-release:
    name: Tag release
    needs: publish-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install source distribution
        run: pip install "$(ls dist/*.tar.gz)"

      - name: Get source distribution version
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          DISTRO_NAME="${REPO_NAME//-/_}"
          TAG_VERSION=$(python -c "from importlib.metadata import version; print(version('${DISTRO_NAME}'))")
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
          echo "Detected version: ${TAG_VERSION}"

      - name: Create Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference

          API_URL="${{ github.api_url }}/repos/${{ github.repository }}/git/refs"
          API_VERSION="2022-11-28"

          TAG_NAME="v${{ env.TAG_VERSION }}"
          REF_SHA="${{ github.sha }}"

          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -L --request POST \
            --url "${API_URL}" \
            --header "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
            --header "Content-Type: application/json" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: ${API_VERSION}" \
            --data "{
              \"ref\": \"refs/tags/${TAG_NAME}\",
              \"sha\": \"${REF_SHA}\"
            }")

          if [[ "$RESPONSE" -ne 201 ]]; then
            echo "❌ GitHub API request failed with status code: $RESPONSE"
            cat response.json
            exit 1
          fi
